// =====================================================================
// Catalogo de materiais.
// Cada item define SUAS medidas, atributos, unidades (de magnitude
// equivalente entre si), cores, faixa de preco em BRL para essa unidade
// e fabricantes que realmente produzem aquele item.
//
// Formato: [nome, medidas, atributos, unidades, cores, [precoMin, precoMax], marcas]
// =====================================================================

export const CATALOGO = {
  'Material Elétrico': [
    ['CABO FLEXÍVEL', ['1,5MM²', '2,5MM²', '4MM²', '6MM²', '10MM²', '16MM²'], ['750V', '0,6/1KV', 'ANTICHAMA'], ['M'], ['AZUL', 'PRETO', 'VERMELHO', 'VERDE', 'BRANCO'], [1.4, 26], ['Prysmian', 'Cobrecom', 'Sil', 'Induscabos', 'Corfio']],
    ['CABO PP', ['2X1,5MM²', '2X2,5MM²', '3X2,5MM²', '4X4MM²'], ['300/500V', '0,6/1KV'], ['M'], ['PRETO', 'CINZA'], [3.2, 34], ['Prysmian', 'Cobrecom', 'Sil', 'Corfio']],
    ['DISJUNTOR MONOPOLAR', ['10A', '16A', '20A', '25A', '32A', '40A'], ['CURVA B', 'CURVA C', 'DIN'], ['UN', 'PC'], [], [11, 34], ['Siemens', 'Schneider', 'WEG', 'Steck', 'Soprano']],
    ['DISJUNTOR TRIPOLAR', ['32A', '40A', '63A', '100A', '125A'], ['CURVA C', 'CAIXA MOLDADA'], ['UN', 'PC'], [], [95, 690], ['Siemens', 'Schneider', 'WEG', 'Steck']],
    ['CONTATOR', ['9A', '12A', '18A', '25A', '32A'], ['220V', '380V', 'AC-3'], ['UN', 'PC'], [], [78, 420], ['WEG', 'Siemens', 'Schneider', 'Metaltex']],
    ['RELÉ TÉRMICO', ['4-6A', '7-10A', '9-13A', '17-24A'], ['CLASSE 10', 'REARME MANUAL'], ['UN', 'PC'], [], [92, 340], ['WEG', 'Siemens', 'Schneider']],
    ['LÂMPADA LED BULBO', ['9W', '12W', '15W', '20W'], ['BIVOLT', '6500K', '3000K'], ['UN', 'PC'], [], [7, 26], ['Philips', 'Osram', 'Avant', 'Taschibra', 'Empalux']],
    ['LUMINÁRIA LED', ['18W', '36W', '45W'], ['SOBREPOR', 'EMBUTIR', 'IP20'], ['UN', 'PC'], [], [38, 210], ['Philips', 'Osram', 'Intral', 'Lumicenter']],
    ['REFLETOR LED', ['50W', '100W', '150W', '200W'], ['IP65', 'BIVOLT', '6500K'], ['UN', 'PC'], [], [45, 380], ['Philips', 'Taschibra', 'Avant', 'Intral']],
    ['TOMADA EMBUTIR', ['10A', '20A'], ['2P+T', 'NBR 14136'], ['UN', 'PC'], ['BRANCO', 'PRETO'], [7, 32], ['Pial Legrand', 'Schneider', 'Tramontina', 'Fame', 'Margirius']],
    ['INTERRUPTOR SIMPLES', ['10A'], ['1 TECLA', '2 TECLAS', 'NBR 14136'], ['UN', 'PC'], ['BRANCO'], [7, 29], ['Pial Legrand', 'Schneider', 'Tramontina', 'Margirius']],
    ['ELETRODUTO PVC', ['3/4"', '1"', '1.1/4"', '2"'], ['RÍGIDO', 'FLEXÍVEL CORRUGADO'], ['BAR'], ['AMARELO', 'CINZA', 'PRETO'], [9, 64], ['Tigre', 'Amanco', 'Krona', 'Adtex']],
    ['FITA ISOLANTE', ['19MMX10M', '19MMX20M'], ['ANTICHAMA', '750V'], ['UN', 'RL'], ['PRETO', 'VERMELHO', 'AZUL', 'VERDE'], [4.5, 19], ['3M', 'Adere', 'Alltak', 'Tigre']],
    ['TERMINAL PRÉ-ISOLADO', ['1,5MM²', '2,5MM²', '4MM²', '6MM²'], ['OLHAL', 'GARFO', 'PINO'], ['CENTO'], [], [18, 92], ['Intelli', 'Decorlux', 'Tramontina', 'Steck']],
    ['FUSÍVEL NH', ['32A', '63A', '100A', '160A'], ['TAMANHO 00', 'TAMANHO 1', 'GL/GG'], ['UN', 'PC'], [], [22, 145], ['Siemens', 'WEG', 'Schneider', 'Steck']],
    ['BOTOEIRA', ['22MM'], ['PULSO', 'RETENÇÃO', 'EMERGÊNCIA'], ['UN', 'PC'], ['VERDE', 'VERMELHO', 'PRETO'], [14, 78], ['WEG', 'Siemens', 'Metaltex', 'Steck']],
    ['SINALEIRO LED', ['22MM'], ['24V', '220V'], ['UN', 'PC'], ['VERDE', 'VERMELHO', 'AMARELO', 'BRANCO'], [12, 62], ['WEG', 'Siemens', 'Metaltex', 'Steck']],
    ['INVERSOR DE FREQUÊNCIA', ['1CV', '2CV', '3CV', '5CV', '7,5CV'], ['220V MONO', '380V TRI'], ['UN'], [], [860, 5400], ['WEG', 'Siemens', 'Schneider', 'Delta']],
    ['QUADRO DE DISTRIBUIÇÃO', ['12 DIN', '18 DIN', '24 DIN', '32 DIN'], ['EMBUTIR', 'SOBREPOR', 'IP40'], ['UN'], ['BRANCO'], [78, 460], ['Cemar', 'Steck', 'Schneider', 'Tigre']],
    ['CANALETA', ['20X10MM', '30X20MM', '50X30MM'], ['ADESIVADA', 'COM DIVISÓRIA'], ['BAR'], ['BRANCO'], [8, 46], ['Ilumi', 'Steck', 'Tigre', 'Adtex']],
  ],

  'Material Hidráulico': [
    ['TUBO PVC SOLDÁVEL', ['20MM', '25MM', '32MM', '40MM', '50MM', '75MM'], ['NBR 5648', 'PN 750KPA'], ['BAR'], ['BRANCO'], [14, 128], ['Tigre', 'Amanco', 'Krona', 'Plastilit', 'Corr Plastik']],
    ['TUBO PVC ESGOTO', ['40MM', '50MM', '75MM', '100MM'], ['SÉRIE NORMAL', 'NBR 5688'], ['BAR'], ['BRANCO'], [22, 165], ['Tigre', 'Amanco', 'Krona', 'Plastilit']],
    ['JOELHO 90°', ['20MM', '25MM', '32MM', '40MM', '50MM'], ['SOLDÁVEL', 'ROSCÁVEL'], ['UN', 'PC'], ['BRANCO', 'MARROM'], [0.9, 12], ['Tigre', 'Amanco', 'Krona', 'Herc']],
    ['JOELHO 45°', ['25MM', '32MM', '40MM', '50MM'], ['SOLDÁVEL'], ['UN', 'PC'], ['BRANCO'], [1.2, 14], ['Tigre', 'Amanco', 'Krona', 'Herc']],
    ['TÊ SOLDÁVEL', ['20MM', '25MM', '32MM', '50MM'], ['NBR 5648'], ['UN', 'PC'], ['BRANCO'], [1.3, 18], ['Tigre', 'Amanco', 'Krona', 'Herc']],
    ['LUVA SOLDÁVEL', ['20MM', '25MM', '32MM', '40MM'], ['NBR 5648'], ['UN', 'PC'], ['BRANCO'], [0.8, 9], ['Tigre', 'Amanco', 'Krona', 'Herc']],
    ['BUCHA DE REDUÇÃO', ['32X25MM', '40X32MM', '50X40MM'], ['SOLDÁVEL', 'LONGA'], ['UN', 'PC'], ['BRANCO'], [1.5, 11], ['Tigre', 'Amanco', 'Krona']],
    ['REGISTRO ESFERA', ['1/2"', '3/4"', '1"', '1.1/2"', '2"'], ['PN16', 'ROSCÁVEL', 'BRONZE'], ['UN', 'PC'], [], [26, 285], ['Docol', 'Deca', 'Tigre', 'Fortlev', 'Niagara']],
    ['REGISTRO GAVETA', ['3/4"', '1"', '1.1/2"'], ['BRUTO', 'COM ACABAMENTO'], ['UN', 'PC'], [], [42, 240], ['Docol', 'Deca', 'Fabrimar']],
    ['VÁLVULA RETENÇÃO', ['1/2"', '3/4"', '1"', '2"'], ['VERTICAL', 'HORIZONTAL', 'PN16'], ['UN', 'PC'], [], [34, 265], ['Docol', 'Deca', 'Niagara', 'Tigre']],
    ['ADESIVO PVC', ['75G', '175G', '850G'], ['BISNAGA', 'LATA'], ['UN', 'TB'], [], [9, 68], ['Tigre', 'Amanco', 'Krona']],
    ['FITA VEDA ROSCA', ['18MMX10M', '18MMX25M', '18MMX50M'], ['PTFE'], ['UN', 'RL'], ['BRANCO'], [2.5, 14], ['Tigre', 'Amanco', '3M', 'Tramontina']],
    ['BOMBA CENTRÍFUGA', ['1/2CV', '1CV', '2CV', '3CV'], ['MONOFÁSICA', 'TRIFÁSICA', 'FERRO FUNDIDO'], ['UN'], [], [640, 3900], ['Schneider Motobombas', 'Dancor', 'KSB', 'Thebe']],
    ["CAIXA D'ÁGUA", ['310L', '500L', '1000L', '2000L'], ['POLIETILENO', 'COM TAMPA'], ['UN'], ['AZUL'], [190, 1450], ['Fortlev', 'Tigre', 'Acqualimp', 'Bakof']],
    ['CONEXÃO PPR', ['20MM', '25MM', '32MM'], ['TERMOFUSÃO', 'PN20'], ['UN', 'PC'], ['VERDE'], [2.4, 22], ['Amanco', 'Tigre', 'Krona']],
    ['HIDRÔMETRO', ['1/2"', '3/4"'], ['CLASSE B', 'UNIJATO'], ['UN'], [], [110, 420], ['LAO', 'Saga', 'Elster']],
    ['TORNEIRA BOIA', ['1/2"', '3/4"'], ['VAZÃO ALTA', 'BALÃO PLÁSTICO'], ['UN', 'PC'], [], [18, 96], ['Docol', 'Censi', 'Astra', 'Tigre']],
    ['ANEL DE VEDAÇÃO', ['40MM', '50MM', '100MM'], ['BORRACHA', 'PARA ESGOTO'], ['UN'], ['PRETO'], [1.8, 14], ['Tigre', 'Amanco', 'Vedabras']],
    ['NIPLE GALVANIZADO', ['1/2"', '3/4"', '1"', '2"'], ['ROSCÁVEL', 'NBR 6414'], ['UN', 'PC'], [], [4.5, 38], ['Tupy', 'Ferrero', 'Alvenius']],
    ['VÁLVULA ESFERA', ['1/2"', '1"', '2"'], ['BRONZE', 'PASSAGEM PLENA'], ['UN', 'PC'], [], [32, 310], ['Docol', 'Niagara', 'Deca', 'Valmicro']],
  ],

  'EPI e Segurança': [
    ['CAPACETE DE SEGURANÇA', ['CLASSE B'], ['CA 31469', 'COM JUGULAR', 'ABA FRONTAL'], ['UN'], ['BRANCO', 'AMARELO', 'AZUL', 'VERMELHO'], [17, 68], ['MSA', '3M', 'Camper', 'Plastcor', 'Delta Plus']],
    ['LUVA NITRÍLICA', ['TAM P', 'TAM M', 'TAM G', 'TAM GG'], ['CA 28011', 'PALMA ANTIDERRAPANTE'], ['PAR'], ['VERDE', 'AZUL', 'PRETO'], [3.2, 16], ['Volk', 'Danny', 'Vicsa', 'Nitriflex', 'Super Safety']],
    ['LUVA VAQUETA', ['TAM M', 'TAM G', 'TAM GG'], ['CA 30107', 'PUNHO 7CM', 'PUNHO 15CM'], ['PAR'], [], [9, 34], ['Bracol', 'Danny', 'Volk', 'Kalipso']],
    ['LUVA ISOLANTE', ['CLASSE 0', 'CLASSE 2'], ['CA 29157', '1000V', '17000V'], ['PAR'], [], [180, 720], ['Salisbury', 'Orion', 'Vicsa']],
    ['ÓCULOS DE PROTEÇÃO', ['INCOLOR', 'FUMÊ'], ['CA 34082', 'ANTIEMBAÇANTE', 'ANTIRRISCO'], ['UN'], [], [6, 42], ['3M', 'MSA', 'Kalipso', 'Danny', 'Vicsa']],
    ['PROTETOR AURICULAR', ['PLUG', 'CONCHA'], ['CA 39132', 'NRRsf 16dB', 'NRRsf 21dB'], ['PAR'], [], [2.4, 58], ['3M', 'MSA', 'Kalipso', 'Danny']],
    ['MÁSCARA PFF2', ['SEM VÁLVULA', 'COM VÁLVULA'], ['CA 38503', 'DESCARTÁVEL'], ['UN'], ['BRANCO'], [1.8, 9], ['3M', 'Delta Plus', 'Camper', 'Tayco']],
    ['RESPIRADOR SEMIFACIAL', ['TAM M', 'TAM G'], ['CA 33002', 'SILICONE', 'DUPLO FILTRO'], ['UN'], [], [95, 340], ['3M', 'MSA', 'Air Safety']],
    ['BOTINA DE SEGURANÇA', ['Nº 38', 'Nº 39', 'Nº 40', 'Nº 41', 'Nº 42', 'Nº 43', 'Nº 44'], ['CA 37021', 'BICO COMPOSITE', 'ELÁSTICO'], ['PAR'], ['PRETO', 'MARROM'], [78, 260], ['Marluvas', 'Bracol', 'Fujiwara', 'Cartom', 'Bompel']],
    ['CINTO PARAQUEDISTA', ['TAM ÚNICO'], ['CA 35519', '5 PONTOS', 'NR-35'], ['UN'], [], [190, 640], ['MSA', 'Altiseg', 'Vicsa', 'Petzl']],
    ['TALABARTE', ['1,5M', '2,0M'], ['CA 35520', 'DUPLO Y', 'COM ABSORVEDOR'], ['UN'], [], [160, 580], ['MSA', 'Altiseg', 'Vicsa', 'Petzl']],
    ['AVENTAL RASPA', ['70CM', '90CM', '120CM'], ['CA 30112', 'PARA SOLDA'], ['UN'], [], [28, 92], ['Bracol', 'Kalipso', 'Danny', 'Volk']],
    ['PERNEIRA', ['60CM'], ['CA 31002', 'RASPA', 'COM FECHO'], ['PAR'], [], [24, 78], ['Bracol', 'Kalipso', 'Volk']],
    ['COLETE REFLETIVO', ['TAM M', 'TAM G', 'TAM GG'], ['CA 32117', 'FAIXA REFLETIVA'], ['UN'], ['LARANJA', 'AMARELO', 'VERDE'], [11, 46], ['Plastcor', 'Danny', 'Vicsa', 'Camper']],
    ['CONE DE SINALIZAÇÃO', ['50CM', '75CM'], ['PVC FLEXÍVEL', 'COM REFLETIVO'], ['UN'], ['LARANJA'], [24, 96], ['Plastcor', 'Kalipso', 'Vonder']],
    ['FITA ZEBRADA', ['70MMX200M'], ['POLIETILENO', 'DEMARCAÇÃO'], ['RL'], ['AMARELO', 'BRANCO'], [12, 38], ['Plastcor', 'Adere', 'Kalipso']],
    ['PLACA DE SINALIZAÇÃO', ['20X30CM', '30X40CM'], ['PVC 2MM', 'FOTOLUMINESCENTE'], ['UN', 'PC'], [], [8, 46], ['Sinalize', 'Plastcor', 'Encartale']],
    ['MANGA DE RASPA', ['45CM', '60CM'], ['CA 30115', 'PARA SOLDA'], ['PAR'], [], [19, 62], ['Bracol', 'Kalipso', 'Volk']],
    ['CAPA DE CHUVA', ['TAM M', 'TAM G', 'TAM GG'], ['CA 31018', 'PVC FORRADO'], ['UN'], ['AMARELO', 'VERDE'], [22, 88], ['Plastcor', 'Kalipso', 'Danny']],
    ['PROTETOR FACIAL', ['8"'], ['CA 34083', 'INCOLOR', 'COM CATRACA'], ['UN'], [], [26, 98], ['3M', 'MSA', 'Kalipso', 'Vicsa']],
  ],

  'Ferramentas': [
    ['CHAVE DE FENDA', ['1/8"X4"', '3/16"X6"', '1/4"X6"'], ['ISOLADA 1000V', 'CABO ANATÔMICO'], ['UN'], [], [9, 62], ['Tramontina', 'Gedore', 'Belzer', 'Stanley', 'Vonder']],
    ['CHAVE PHILLIPS', ['Nº1X4"', 'Nº2X6"', 'Nº3X8"'], ['ISOLADA 1000V', 'PONTA IMANTADA'], ['UN'], [], [10, 68], ['Tramontina', 'Gedore', 'Belzer', 'Stanley']],
    ['CHAVE COMBINADA', ['8MM', '10MM', '13MM', '17MM', '19MM', '22MM'], ['CROMO VANÁDIO', 'ESPELHADA'], ['UN'], [], [14, 96], ['Gedore', 'Tramontina', 'Belzer', 'Sata', 'Vonder']],
    ['JOGO DE SOQUETES', ['1/4"', '1/2"'], ['CROMO VANÁDIO', '40 PEÇAS', '94 PEÇAS'], ['JG'], [], [180, 1250], ['Gedore', 'Tramontina', 'Sata', 'Stanley']],
    ['ALICATE UNIVERSAL', ['6"', '8"'], ['ISOLADO 1000V', 'CROMO VANÁDIO'], ['UN'], [], [32, 180], ['Gedore', 'Tramontina', 'Belzer', 'Irwin']],
    ['ALICATE DE CORTE', ['6"', '8"'], ['ISOLADO 1000V', 'DIAGONAL'], ['UN'], [], [29, 165], ['Gedore', 'Tramontina', 'Belzer', 'Irwin']],
    ['MARTELO UNHA', ['25MM', '27MM', '29MM'], ['CABO MADEIRA', 'CABO FIBRA'], ['UN'], [], [28, 120], ['Tramontina', 'Vonder', 'Stanley', 'Worker']],
    ['MARRETA', ['1KG', '2KG', '5KG'], ['CABO MADEIRA', 'OITAVADA'], ['UN'], [], [42, 210], ['Tramontina', 'Vonder', 'Worker']],
    ['SERRA COPO', ['22MM', '35MM', '50MM', '68MM'], ['BIMETAL', 'AÇO RÁPIDO'], ['UN'], [], [34, 180], ['Starrett', 'Bosch', 'Irwin', 'Vonder']],
    ['FURADEIRA DE IMPACTO', ['550W', '710W', '850W'], ['BIVOLT', '220V', 'MANDRIL 13MM'], ['UN'], [], [280, 980], ['Bosch', 'Makita', 'DeWalt', 'Vonder', 'Stanley']],
    ['PARAFUSADEIRA', ['12V', '18V'], ['À BATERIA', 'COM 2 BATERIAS'], ['UN'], [], [340, 1680], ['Bosch', 'Makita', 'DeWalt', 'Vonder']],
    ['ESMERILHADEIRA', ['4.1/2"', '7"'], ['710W', '2200W', '220V'], ['UN'], [], [230, 1150], ['Bosch', 'Makita', 'DeWalt', 'Vonder']],
    ['MORSA DE BANCADA', ['4"', '6"', '8"'], ['FERRO FUNDIDO', 'BASE GIRATÓRIA'], ['UN'], [], [180, 890], ['Vonder', 'Marcon', 'Tramontina']],
    ['TRENA', ['5M', '7,5M', '10M'], ['TRAVA AUTOMÁTICA', 'FITA 25MM'], ['UN'], [], [18, 92], ['Starrett', 'Stanley', 'Tramontina', 'Vonder', 'Irwin']],
    ['PAQUÍMETRO', ['150MM', '200MM', '300MM'], ['DIGITAL', 'ANALÓGICO', 'INOX'], ['UN'], [], [95, 780], ['Mitutoyo', 'Starrett', 'Digimess', 'Vonder']],
    ['MULTÍMETRO DIGITAL', ['600V', '1000V'], ['CAT III', 'TRUE RMS', 'COM CAPACÍMETRO'], ['UN'], [], [110, 890], ['Fluke', 'Minipa', 'Hikari', 'Politerm']],
    ['TORQUÍMETRO', ['1/2"', '3/4"'], ['ESTALO 20-210NM', 'ESTALO 70-350NM'], ['UN'], [], [320, 1450], ['Gedore', 'Tramontina', 'Sata', 'Belzer']],
    ['DISCO DE CORTE', ['4.1/2"X1,0MM', '7"X2,0MM', '12"X3,0MM'], ['PARA INOX', 'PARA FERRO'], ['UN'], [], [3.5, 32], ['Norton', 'Bosch', 'Makita', '3M', 'Carborundum']],
    ['BROCA AÇO RÁPIDO', ['3MM', '5MM', '8MM', '10MM', '13MM'], ['HSS', 'PARA METAL'], ['UN'], [], [4, 48], ['Bosch', 'Irwin', 'Twill', 'Vonder']],
    ['NÍVEL DE BOLHA', ['30CM', '60CM', '100CM'], ['ALUMÍNIO', '3 BOLHAS'], ['UN'], [], [24, 145], ['Stanley', 'Vonder', 'Tramontina', 'Starrett']],
  ],

  'Material de Construção': [
    ['CIMENTO PORTLAND', ['50KG'], ['CP-II-E-32', 'CP-IV-32', 'NBR 16697'], ['SC50'], [], [32, 48], ['Votorantim', 'InterCement', 'CSN Cimentos', 'Mizu', 'Nassau']],
    ['ARGAMASSA COLANTE', ['20KG'], ['AC-I', 'AC-II', 'AC-III'], ['SC'], ['CINZA'], [12, 42], ['Quartzolit', 'Votomassa', 'Fortaleza', 'Ceral']],
    ['REJUNTE', ['1KG', '5KG'], ['ACRÍLICO', 'FLEXÍVEL'], ['PCT'], ['BRANCO', 'CINZA', 'BEGE'], [6, 46], ['Quartzolit', 'Portokoll', 'Fortaleza']],
    ['CAL HIDRATADA', ['20KG'], ['CH-III', 'NBR 7175'], ['SC'], [], [14, 28], ['Itaú', 'Supercal', 'Qualical']],
    ['AREIA MÉDIA', ['LAVADA'], ['NBR 7211', 'A GRANEL'], ['M3'], [], [95, 190], ['Mineradora Regional', 'Porto de Areia Local']],
    ['BRITA', ['Nº0', 'Nº1', 'Nº2'], ['NBR 7211', 'GRANÍTICA'], ['M3'], [], [110, 220], ['Pedreira Regional', 'Mineradora Local']],
    ['VERGALHÃO CA-50', ['6,3MM', '8,0MM', '10,0MM', '12,5MM'], ['NERVURADO', 'BARRA 12M'], ['BAR'], [], [26, 98], ['Gerdau', 'ArcelorMittal', 'Aço Verde', 'Simec']],
    ['TELA SOLDADA', ['Q-92', 'Q-138', 'Q-196'], ['PAINEL 2,45X6,00M'], ['PC'], [], [180, 520], ['Gerdau', 'ArcelorMittal', 'Belgo']],
    ['PERFIL METÁLICO', ['U 50X25', 'U 75X40', 'W 150X13'], ['GALVANIZADO', 'BARRA 6M'], ['BAR'], [], [98, 690], ['Gerdau', 'ArcelorMittal', 'Perfilor']],
    ['CHAPA GALVANIZADA', ['#18', '#20', '#22'], ['1,20X2,00M', 'ZINCADA'], ['CH'], [], [160, 480], ['ArcelorMittal', 'CSN', 'Usiminas']],
    ['TIJOLO CERÂMICO', ['9X19X19CM', '11,5X19X19CM'], ['8 FUROS', '6 FUROS'], ['MIL'], [], [780, 1650], ['Cerâmica Regional', 'Selecta', 'Pauluzzi']],
    ['BLOCO DE CONCRETO', ['14X19X39CM', '19X19X39CM'], ['ESTRUTURAL', 'VEDAÇÃO'], ['UN'], [], [3.2, 9.5], ['Tatu Pré-moldados', 'Blocaus', 'Premo']],
    ['IMPERMEABILIZANTE', ['3,6L', '18L'], ['BASE ACRÍLICA', 'MANTA LÍQUIDA'], ['BD', 'GL'], ['BRANCO', 'CINZA'], [68, 480], ['Sika', 'Vedacit', 'Denver', 'Quartzolit']],
    ['MANTA ASFÁLTICA', ['3MM', '4MM'], ['ROLO 10M²', 'ALUMINIZADA'], ['RL'], [], [180, 620], ['Sika', 'Denver', 'Viapol', 'Vedacit']],
    ['TÁBUA DE PINUS', ['2,5X30CM'], ['3M', '4M', 'APLAINADA'], ['PC'], [], [42, 145], ['Madeireira Regional', 'Berneck', 'Arauco']],
    ['COMPENSADO NAVAL', ['10MM', '15MM', '18MM'], ['2,20X1,60M', 'RESINADO'], ['CH'], [], [140, 420], ['Berneck', 'Guararapes', 'Sudati']],
    ['TELHA FIBROCIMENTO', ['4MM', '6MM'], ['ONDULADA 2,44M', 'ONDULADA 3,66M'], ['PC'], [], [58, 180], ['Brasilit', 'Eternit', 'Imbralit', 'Confibra']],
    ['PORCELANATO', ['60X60CM', '80X80CM'], ['ACETINADO', 'POLIDO', 'PEI-4'], ['M2'], ['BEGE', 'CINZA', 'BRANCO'], [42, 190], ['Portobello', 'Eliane', 'Cecrisa', 'Biancogres']],
    ['MASSA CORRIDA', ['18L'], ['PVA', 'ACRÍLICA'], ['BD'], ['BRANCO'], [72, 260], ['Suvinil', 'Coral', 'Iquine', 'Sherwin Williams']],
    ['GESSO', ['40KG'], ['EM PÓ', 'PARA FUNDIÇÃO'], ['SC'], ['BRANCO'], [22, 46], ['Gipsita', 'Supergesso', 'Gesso Rio Branco']],
  ],

  'Informática e Telecom': [
    ['NOTEBOOK CORPORATIVO', ['14"', '15,6"'], ['I5 8GB 256GB', 'I7 16GB 512GB', 'RYZEN 5 8GB'], ['UN'], [], [3200, 9800], ['Dell', 'Lenovo', 'HP', 'Positivo', 'Acer']],
    ['DESKTOP CORPORATIVO', ['SFF', 'TORRE'], ['I5 8GB 256GB', 'I7 16GB 512GB'], ['UN'], [], [2800, 8200], ['Dell', 'Lenovo', 'HP', 'Positivo']],
    ['MONITOR LED', ['21,5"', '24"', '27"'], ['FULL HD', 'IPS', 'COM AJUSTE DE ALTURA'], ['UN'], ['PRETO'], [620, 2400], ['Dell', 'LG', 'Samsung', 'AOC', 'Philips']],
    ['TECLADO ABNT2', ['PADRÃO'], ['USB', 'SEM FIO', 'SLIM'], ['UN'], ['PRETO'], [38, 320], ['Logitech', 'Dell', 'HP', 'Multilaser', 'Microsoft']],
    ['MOUSE ÓPTICO', ['1000DPI', '1600DPI'], ['USB', 'SEM FIO'], ['UN'], ['PRETO'], [22, 280], ['Logitech', 'Dell', 'HP', 'Multilaser', 'Microsoft']],
    ['HEADSET USB', ['BIAURICULAR'], ['COM MICROFONE', 'CANCELAMENTO DE RUÍDO'], ['UN'], ['PRETO'], [98, 890], ['Logitech', 'Jabra', 'Plantronics', 'Multilaser']],
    ['SWITCH GERENCIÁVEL', ['24 PORTAS', '48 PORTAS'], ['GIGABIT', 'POE', 'RACK 19"'], ['UN'], [], [1400, 8900], ['Cisco', 'TP-Link', 'Intelbras', 'HPE Aruba', 'Ubiquiti']],
    ['ROTEADOR', ['AC1200', 'AX1800'], ['DUAL BAND', 'HOMOLOGADO ANATEL'], ['UN'], [], [180, 980], ['TP-Link', 'Intelbras', 'Mercusys', 'Ubiquiti']],
    ['ACCESS POINT', ['AC1200', 'AX3000'], ['POE', 'TETO', 'HOMOLOGADO ANATEL'], ['UN'], [], [340, 1900], ['Ubiquiti', 'Intelbras', 'TP-Link', 'Cisco']],
    ['CABO DE REDE CAT6', ['100M', '305M'], ['U/UTP', 'CMX', 'HOMOLOGADO ANATEL'], ['CX'], ['AZUL', 'CINZA'], [280, 1450], ['Furukawa', 'Nexans', 'Intelbras', 'Legrand']],
    ['PATCH PANEL', ['24 PORTAS', '48 PORTAS'], ['CAT6', 'RACK 19"'], ['UN'], [], [280, 1200], ['Furukawa', 'Nexans', 'Intelbras', 'Legrand']],
    ['RACK DE PAREDE', ['12U', '16U', '20U'], ['PROFUNDIDADE 570MM', 'PORTA DE VIDRO'], ['UN'], ['PRETO'], [420, 1600], ['Intelbras', 'Nilko', 'Furukawa']],
    ['NOBREAK', ['700VA', '1500VA', '3000VA'], ['SENOIDAL', 'BIVOLT', 'INTERATIVO'], ['UN'], [], [420, 4800], ['APC', 'SMS', 'Intelbras', 'TS Shara']],
    ['SSD', ['240GB', '480GB', '1TB'], ['SATA III', 'NVMe M.2'], ['UN'], [], [140, 720], ['Kingston', 'Samsung', 'Western Digital', 'Crucial']],
    ['MEMÓRIA RAM DDR4', ['8GB', '16GB', '32GB'], ['2666MHz', '3200MHz', 'UDIMM'], ['UN'], [], [140, 780], ['Kingston', 'Crucial', 'Corsair', 'Samsung']],
    ['IMPRESSORA LASER', ['MONOCROMÁTICA', 'MULTIFUNCIONAL'], ['35PPM', 'DUPLEX', 'REDE'], ['UN'], [], [1200, 6800], ['HP', 'Brother', 'Lexmark', 'Epson']],
    ['TONER', ['ALTO RENDIMENTO', 'PADRÃO'], ['ORIGINAL', 'COMPATÍVEL'], ['UN'], ['PRETO', 'AZUL', 'AMARELO', 'VERMELHO'], [88, 980], ['HP', 'Brother', 'Lexmark', 'Chinamate']],
    ['WEBCAM HD', ['720P', '1080P'], ['COM MICROFONE', 'USB'], ['UN'], ['PRETO'], [88, 620], ['Logitech', 'Intelbras', 'Multilaser']],
    ['HD EXTERNO', ['1TB', '2TB', '4TB'], ['USB 3.0', 'PORTÁTIL'], ['UN'], ['PRETO'], [340, 1250], ['Seagate', 'Western Digital', 'Toshiba']],
    ['ADAPTADOR USB-C', ['HDMI', 'MULTIPORTAS'], ['4K 60HZ', 'COM RJ45'], ['UN'], [], [68, 480], ['Logitech', 'Dell', 'Multilaser', 'Baseus']],
  ],

  'Lubrificantes e Químicos': [
    ['ÓLEO LUBRIFICANTE', ['1L', '20L'], ['SAE 15W40 API CI-4', 'SAE 20W50 API SL'], ['L'], [], [22, 48], ['Lubrax', 'Shell', 'Mobil', 'Ipiranga', 'Castrol']],
    ['ÓLEO HIDRÁULICO', ['20L', '200L'], ['ISO VG 46', 'ISO VG 68', 'ANTIDESGASTE'], ['L'], [], [16, 34], ['Lubrax', 'Shell', 'Mobil', 'Ipiranga', 'Total']],
    ['GRAXA DE LÍTIO', ['500G', '1KG', '20KG'], ['NLGI 2', 'EP-2', 'MULTIUSO'], ['KG'], [], [24, 68], ['Lubrax', 'Shell', 'Mobil', 'Bardahl']],
    ['DESENGRAXANTE', ['5L', '20L'], ['BASE ÁGUA', 'BIODEGRADÁVEL', 'CONCENTRADO'], ['L'], [], [12, 42], ['Start Química', 'Radnaq', 'Bardahl', 'Química Industrial']],
    ['SOLVENTE', ['5L', '18L'], ['DIELÉTRICO', 'PARA LIMPEZA'], ['L'], [], [14, 38], ['Radnaq', 'Start Química', 'Ipiranga']],
    ['TINTA ESMALTE', ['900ML', '3,6L'], ['SINTÉTICO', 'BRILHANTE', 'FOSCO'], ['LT', 'GL'], ['BRANCO', 'PRETO', 'AZUL', 'VERMELHO', 'CINZA'], [42, 320], ['Suvinil', 'Coral', 'Sherwin Williams', 'Iquine', 'Lukscolor']],
    ['TINTA ACRÍLICA', ['3,6L', '18L'], ['FOSCA', 'ACETINADA', 'PREMIUM'], ['GL', 'BD'], ['BRANCO', 'BEGE', 'CINZA'], [78, 620], ['Suvinil', 'Coral', 'Sherwin Williams', 'Iquine']],
    ['FUNDO ANTICORROSIVO', ['900ML', '3,6L'], ['ÓXIDO DE FERRO', 'ZARCÃO'], ['LT', 'GL'], ['VERMELHO', 'CINZA'], [38, 280], ['Suvinil', 'Coral', 'Lukscolor', 'Sherwin Williams']],
    ['THINNER', ['900ML', '5L'], ['PARA ESMALTE', 'PARA LIMPEZA'], ['LT', 'L'], [], [16, 62], ['Radnaq', 'Coral', 'Anjo', 'Iquine']],
    ['DETERGENTE INDUSTRIAL', ['5L', '20L'], ['ALCALINO', 'NEUTRO', 'CONCENTRADO'], ['L'], [], [9, 32], ['Start Química', 'Audax', 'Química Industrial']],
    ['DESINFETANTE', ['5L', '20L'], ['QUATERNÁRIO DE AMÔNIO', 'BACTERICIDA'], ['L'], [], [8, 28], ['Start Química', 'Audax', 'Ypê Profissional']],
    ['ÁLCOOL ISOPROPÍLICO', ['1L', '5L'], ['99,8%', 'PARA ELETRÔNICA'], ['L'], [], [28, 72], ['Implastec', 'Radnaq', 'Química Moderna']],
    ['REMOVEDOR DE FERRUGEM', ['500ML', '5L'], ['GEL', 'LÍQUIDO'], ['FR', 'L'], [], [22, 96], ['Bardahl', 'Radnaq', 'Start Química', 'WD-40']],
    ['FLUIDO DE CORTE', ['5L', '20L'], ['SOLÚVEL', 'SEMISSINTÉTICO'], ['L'], [], [18, 52], ['Quimatic Tapmatic', 'Blaser', 'Castrol', 'Bardahl']],
    ['ADITIVO RADIADOR', ['1L', '5L'], ['CONCENTRADO', 'PRONTO USO', 'ORGÂNICO'], ['L'], ['VERDE', 'VERMELHO'], [14, 46], ['Bardahl', 'Paraflu', 'Radiex', 'Wurth']],
    ['SILICONE SPRAY', ['300ML', '400ML'], ['LUBRIFICANTE', 'DESMOLDANTE'], ['UN'], [], [18, 64], ['WD-40', 'Bardahl', 'Wurth', 'Orbi']],
    ['ÓLEO DE CORRENTE', ['1L', '20L'], ['ADESIVO', 'ISO VG 100'], ['L'], [], [22, 58], ['Lubrax', 'Shell', 'Mobil', 'Bardahl']],
    ['VERNIZ', ['900ML', '3,6L'], ['MARÍTIMO', 'ACRÍLICO', 'BRILHANTE'], ['LT', 'GL'], ['INCOLOR'], [48, 290], ['Suvinil', 'Coral', 'Montana', 'Sparlack']],
    ['CERA AUTOMOTIVA', ['200ML', '500ML'], ['CARNAÚBA', 'CRISTALIZADORA'], ['FR'], [], [22, 98], ['Bardahl', 'Vonixx', '3M', 'Meguiars']],
    ['SABÃO LÍQUIDO', ['5L', '20L'], ['NEUTRO', 'PARA MÃOS'], ['L'], [], [7, 24], ['Start Química', 'Audax', 'Ypê Profissional']],
  ],

  'Rolamentos e Transmissão': [
    ['ROLAMENTO RÍGIDO DE ESFERAS', ['6203', '6204', '6205', '6206', '6305', '6308'], ['BLINDADO 2Z', 'VEDADO 2RS', 'C3'], ['UN', 'PC'], [], [18, 240], ['SKF', 'NSK', 'FAG', 'NTN', 'Nachi']],
    ['ROLAMENTO AUTOCOMPENSADOR', ['22208', '22210', '22213'], ['ROLETES', 'C3'], ['UN', 'PC'], [], [280, 1450], ['SKF', 'NSK', 'FAG', 'NTN']],
    ['ROLAMENTO CÔNICO', ['30205', '30206', '32208'], ['CARGA COMBINADA'], ['UN', 'PC'], [], [42, 320], ['Timken', 'SKF', 'NSK', 'FAG']],
    ['ROLAMENTO AXIAL', ['51105', '51107', '51204'], ['ESFERAS', 'ESCORA SIMPLES'], ['UN', 'PC'], [], [38, 280], ['SKF', 'NSK', 'FAG', 'NTN']],
    ['MANCAL DE PAREDE', ['UCP 204', 'UCP 205', 'UCP 207'], ['FERRO FUNDIDO', 'COM ROLAMENTO'], ['UN', 'PC'], [], [62, 340], ['SKF', 'NSK', 'FYH', 'Asahi']],
    ['MANCAL FLANGEADO', ['UCF 204', 'UCF 206', 'UCF 208'], ['4 FUROS', 'COM ROLAMENTO'], ['UN', 'PC'], [], [68, 360], ['SKF', 'NSK', 'FYH', 'Asahi']],
    ['CORREIA EM V', ['A-45', 'A-60', 'B-60', 'B-75', 'C-90'], ['PERFIL A', 'PERFIL B', 'PERFIL C'], ['UN', 'PC'], [], [22, 190], ['Gates', 'Optibelt', 'Continental', 'Dayco']],
    ['CORREIA DENTADA', ['HTD 5M', 'HTD 8M'], ['LARGURA 15MM', 'LARGURA 25MM'], ['UN', 'PC'], [], [48, 320], ['Gates', 'Optibelt', 'Continental']],
    ['CORRENTE DE ROLOS', ['ASA 40', 'ASA 50', 'ASA 60', 'ASA 80'], ['SIMPLES', 'DUPLA'], ['M'], [], [28, 180], ['Daido', 'Tsubaki', 'Renold', 'Rexnord']],
    ['POLIA EM V', ['2 CANAIS', '3 CANAIS'], ['PERFIL A', 'PERFIL B', 'FERRO FUNDIDO'], ['UN', 'PC'], [], [58, 420], ['Mademil', 'Vulkan', 'Rexnord']],
    ['ENGRENAGEM', ['Z=20', 'Z=30', 'Z=40'], ['MÓDULO 2', 'MÓDULO 3', 'AÇO 1045'], ['UN', 'PC'], [], [78, 620], ['Mademil', 'Rexnord', 'Vulkan']],
    ['REDUTOR DE VELOCIDADE', ['1:20', '1:40', '1:60'], ['COROA E ROSCA SEM FIM', 'EIXO VAZADO'], ['UN'], [], [680, 4200], ['WEG', 'SEW Eurodrive', 'Nord', 'Transmotécnica']],
    ['ACOPLAMENTO ELÁSTICO', ['GR 24', 'GR 28', 'GR 38'], ['COM ELEMENTO', 'GARRAS'], ['UN', 'PC'], [], [88, 540], ['Vulkan', 'Antares', 'Rexnord', 'KTR']],
    ['RETENTOR', ['25X47X7', '35X62X10', '50X72X8'], ['NBR', 'COM MOLA'], ['UN', 'PC'], [], [12, 92], ['Sabó', 'Vedabras', 'Corteco', 'SKF']],
    ['BUCHA CÔNICA', ['1610', '2012', '2517'], ['COM PARAFUSOS'], ['UN', 'PC'], [], [42, 280], ['Mademil', 'Optibelt', 'Rexnord']],
    ['ESTICADOR DE CORRENTE', ['ASA 40', 'ASA 60'], ['AUTOMÁTICO', 'COM MOLA'], ['UN'], [], [78, 420], ['Daido', 'Rexnord', 'Mademil']],
    ['EIXO DE TRANSMISSÃO', ['1/2"', '1"', '1.1/2"'], ['AÇO 1045', 'TREFILADO', 'BARRA 6M'], ['BAR'], [], [120, 780], ['Gerdau', 'Villares', 'Aços Especiais']],
    ['ANEL ELÁSTICO', ['25MM', '35MM', '50MM'], ['INTERNO', 'EXTERNO', 'DIN 471'], ['CENTO'], [], [42, 190], ['Ciser', 'Metalúrgica Brasil', 'Rexnord']],
    ['GRAXEIRA', ['1/8"', '1/4"'], ['RETA', '45°', '90°'], ['CENTO'], [], [58, 210], ['Ciser', 'Lubrimais', 'Trico']],
    ['CHAVETA', ['6X6X40MM', '8X7X50MM', '10X8X60MM'], ['AÇO 1045', 'PARALELA'], ['UN'], [], [3.5, 28], ['Ciser', 'Mademil', 'Aços Especiais']],
  ],

  'Material de Escritório': [
    ['PAPEL SULFITE', ['A4 75G', 'A3 75G', 'OFÍCIO 75G'], ['ALCALINO', 'RECICLADO', 'BRANCURA 100%'], ['RS'], ['BRANCO'], [24, 62], ['Chamex', 'Report', 'Copimax', 'Jandaia']],
    ['CANETA ESFEROGRÁFICA', ['0,7MM', '1,0MM'], ['PONTA MÉDIA', 'PONTA FINA', 'CORPO CRISTAL'], ['UN'], ['AZUL', 'PRETO', 'VERMELHO'], [1.2, 8], ['Bic', 'Faber-Castell', 'Pilot', 'Compactor']],
    ['LÁPIS PRETO', ['Nº2', 'HB'], ['SEXTAVADO', 'COM BORRACHA'], ['UN'], [], [0.9, 5], ['Faber-Castell', 'Bic', 'Compactor']],
    ['BORRACHA', ['PEQUENA', 'GRANDE'], ['BRANCA', 'MACIA'], ['UN'], [], [0.8, 6], ['Faber-Castell', 'Mercur', 'Maped']],
    ['MARCA TEXTO', ['PONTA CHANFRADA'], ['FLUORESCENTE', 'RECARREGÁVEL'], ['UN'], ['AMARELO', 'VERDE', 'ROSA', 'AZUL'], [2.8, 14], ['Faber-Castell', 'Pilot', 'Bic', 'Stabilo']],
    ['PINCEL ATÔMICO', ['PONTA CHANFRADA'], ['RECARREGÁVEL', 'PERMANENTE'], ['UN'], ['PRETO', 'AZUL', 'VERMELHO'], [4, 16], ['Pilot', 'Faber-Castell', 'Bic']],
    ['PASTA SUSPENSA', ['OFÍCIO'], ['KRAFT', 'MARMORIZADA', 'COM GRAMPO'], ['UN'], [], [2.2, 9], ['Dello', 'Polycart', 'Frama']],
    ['PASTA AZ', ['LOMBO LARGO', 'LOMBO ESTREITO'], ['OFÍCIO', 'PLASTIFICADA'], ['UN'], ['PRETO', 'AZUL', 'VERMELHO'], [12, 42], ['Dello', 'Frama', 'Polycart', 'Chies']],
    ['GRAMPEADOR', ['26/6', '23/13'], ['MESA', 'ATÉ 25 FOLHAS', 'ATÉ 100 FOLHAS'], ['UN'], [], [22, 190], ['Cis', 'Maped', 'Rapid', 'Jocar']],
    ['GRAMPO', ['26/6', '23/13'], ['GALVANIZADO', 'CAIXA COM 5000'], ['CX'], [], [6, 32], ['Cis', 'Rapid', 'Bacchi']],
    ['CLIPS', ['Nº2/0', 'Nº4/0', 'Nº8/0'], ['GALVANIZADO', 'CAIXA COM 500G'], ['CX'], [], [12, 38], ['Bacchi', 'Cis', 'ACC']],
    ['ENVELOPE', ['114X162MM', '176X250MM', '240X340MM'], ['KRAFT', 'BRANCO', 'SACO'], ['CENTO'], [], [18, 92], ['Scrity', 'Foroni', 'Romitec']],
    ['BLOCO ADESIVO', ['38X50MM', '76X102MM'], ['100 FOLHAS', 'REPOSICIONÁVEL'], ['UN'], ['AMARELO', 'VERDE', 'ROSA'], [3.5, 18], ['3M Post-it', 'Tilibra', 'BRW']],
    ['FITA ADESIVA', ['12MMX30M', '48MMX50M'], ['TRANSPARENTE', 'EMPACOTAMENTO'], ['RL'], [], [2.5, 16], ['3M Scotch', 'Adere', 'Eurocel']],
    ['PAPEL TOALHA', ['20X21CM'], ['INTERFOLHADO', '100% CELULOSE', '2 DOBRAS'], ['FD'], ['BRANCO'], [42, 140], ['Scala', 'Indaial', 'Melhoramentos', 'Snob']],
    ['PAPEL HIGIÊNICO', ['30M', '300M'], ['ROLÃO', 'FOLHA DUPLA', '100% CELULOSE'], ['FD'], ['BRANCO'], [48, 180], ['Scala', 'Neve', 'Personal', 'Indaial']],
    ['COPO DESCARTÁVEL', ['50ML', '180ML', '200ML'], ['NBR 14865', 'PP'], ['CENTO'], ['BRANCO', 'TRANSPARENTE'], [4, 16], ['Copobras', 'Totalplast', 'Minaplast']],
    ['CAFÉ EM PÓ', ['500G', '1KG'], ['TORRADO E MOÍDO', 'TRADICIONAL', 'EXTRAFORTE'], ['KG'], [], [28, 68], ['Pilão', 'Melitta', 'Três Corações', 'Santa Clara']],
    ['AÇÚCAR', ['1KG', '5KG'], ['REFINADO', 'CRISTAL'], ['KG'], [], [4, 9], ['União', 'Caravelas', 'Guarani']],
    ['ÁGUA MINERAL', ['500ML', '1,5L', '20L'], ['SEM GÁS', 'COM GÁS', 'GALÃO RETORNÁVEL'], ['UN'], [], [2, 22], ['Crystal', 'Bonafont', 'Indaiá', 'Minalba']],
  ],

  'Automotivo e Frota': [
    ['PNEU RADIAL', ['175/70 R13', '185/65 R15', '195/55 R16', '215/75 R17.5', '275/80 R22.5'], ['LINHA LEVE', 'LINHA PESADA', 'BORRACHUDO'], ['UN'], [], [320, 3400], ['Michelin', 'Pirelli', 'Goodyear', 'Bridgestone', 'Continental']],
    ['FILTRO DE ÓLEO', ['LINHA LEVE', 'LINHA PESADA'], ['ORIGINAL', 'GENUÍNA', 'PARALELA'], ['UN'], [], [22, 180], ['Mann Filter', 'Tecfil', 'Fram', 'Wega', 'Bosch']],
    ['FILTRO DE AR', ['LINHA LEVE', 'LINHA PESADA'], ['ORIGINAL', 'PARALELA', 'ELEMENTO SECO'], ['UN'], [], [28, 260], ['Mann Filter', 'Tecfil', 'Fram', 'Wega']],
    ['FILTRO DE COMBUSTÍVEL', ['DIESEL', 'FLEX'], ['ORIGINAL', 'SEPARADOR DE ÁGUA'], ['UN'], [], [24, 220], ['Mann Filter', 'Tecfil', 'Bosch', 'Wega']],
    ['BATERIA AUTOMOTIVA', ['60AH', '100AH', '150AH', '180AH'], ['12V', 'LIVRE DE MANUTENÇÃO', 'SELADA'], ['UN'], [], [420, 1980], ['Moura', 'Heliar', 'Zetta', 'Cral']],
    ['PASTILHA DE FREIO', ['DIANTEIRA', 'TRASEIRA'], ['CERÂMICA', 'ORGÂNICA', 'LINHA PESADA'], ['JG'], [], [92, 620], ['Fras-le', 'Cobreq', 'Bosch', 'TRW']],
    ['DISCO DE FREIO', ['256MM', '283MM', '300MM'], ['VENTILADO', 'SÓLIDO'], ['UN'], [], [140, 680], ['Fremax', 'Hipper Freios', 'Bosch', 'TRW']],
    ['AMORTECEDOR', ['DIANTEIRO', 'TRASEIRO'], ['PRESSURIZADO', 'A GÁS'], ['UN'], [], [180, 890], ['Cofap', 'Monroe', 'Nakata', 'KYB']],
    ['CORREIA DENTADA', ['111 DENTES', '123 DENTES', '137 DENTES'], ['ORIGINAL', 'KIT COM TENSOR'], ['UN'], [], [78, 620], ['Gates', 'Contitech', 'Dayco', 'SKF']],
    ['VELA DE IGNIÇÃO', ['RESISTIVA'], ['NÍQUEL', 'IRÍDIO', 'PLATINA'], ['UN'], [], [18, 180], ['NGK', 'Bosch', 'Denso', 'Champion']],
    ['LÂMPADA AUTOMOTIVA', ['H4', 'H7', 'H11'], ['12V 55W', '24V 70W', 'HALÓGENA'], ['UN'], [], [14, 120], ['Philips', 'Osram', 'Bosch']],
    ['PALHETA LIMPADOR', ['16"', '20"', '24"'], ['SILICONE', 'UNIVERSAL'], ['UN'], [], [22, 140], ['Bosch', 'Dyna', 'Valeo', 'Trico']],
    ['RADIADOR', ['LINHA LEVE', 'LINHA PESADA'], ['ALUMÍNIO', 'COM RESERVATÓRIO'], ['UN'], [], [480, 3200], ['Valeo', 'Visconde', 'Behr', 'Denso']],
    ['EMBREAGEM', ['200MM', '215MM', '240MM'], ['KIT COM ROLAMENTO', 'PLATÔ E DISCO'], ['KIT'], [], [420, 2400], ['Sachs', 'Luk', 'Valeo', 'Repsa']],
    ['ROLAMENTO DE RODA', ['DIANTEIRO', 'TRASEIRO'], ['COM CUBO', 'BLINDADO'], ['UN'], [], [98, 680], ['SKF', 'NSK', 'FAG', 'Nakata']],
    ["BOMBA D'ÁGUA", ['LINHA LEVE', 'LINHA PESADA'], ['COM POLIA', 'ORIGINAL'], ['UN'], [], [140, 880], ['Urba', 'Nakata', 'Schadek', 'Gates']],
    ['JUNTA DO CABEÇOTE', ['1,2MM', '1,5MM'], ['METÁLICA', 'MULTICAMADAS'], ['UN'], [], [78, 620], ['Sabó', 'Taranto', 'Victor Reinz']],
    ['TERMINAL DE DIREÇÃO', ['ESQUERDO', 'DIREITO'], ['ORIGINAL', 'PARALELA'], ['UN'], [], [58, 320], ['Nakata', 'Viemar', 'TRW']],
    ['MOLA HELICOIDAL', ['DIANTEIRA', 'TRASEIRA'], ['REFORÇADA', 'ORIGINAL'], ['UN'], [], [120, 640], ['Fabrini', 'Nakata', 'Cofap']],
    ['ESCAPAMENTO', ['INTERMEDIÁRIO', 'TRASEIRO'], ['ALUMINIZADO', 'INOX'], ['UN'], [], [180, 1400], ['Tuper', 'Emissão', 'Bosal']],
  ],
}
